name: nix-build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-push-oci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: |
        nix build \
          -L \
          -o ./imgBase \
          '.#ociImgBase'
    - run: |
        nix build \
          -L \
          -o ./imgGensqlQuery \
          '.#ociImgGensqlQuery'
    - if: github.ref == 'refs/heads/main'
      run: |
        docker load -i ./imgGensqlQuery
        docker push --all-tags probcomp/gensql.query
